services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: nextjs_app
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
    networks:
      - nextjs

  nextjs-prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: nextjs_app_prod
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    networks:
      - nextjs
    profiles:
      - production

networks:
  nextjs:
    driver: bridge