services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs_dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
    networks:
      - nextjs-network

networks:
  nextjs-network:
    driver: bridge